language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t inazrabuu/fe-app-prod-example -f Dockerfile.dev .

script:
  - docker run -e CI=true inazrabuu/fe-app-prod-example npm run test